### ISSUE TITLE
Goodness of fit tests

### ISSUE THREAD

**Issue by embaldridge** [weecology/sad-comparison#110]
Need parametric bootstrapping goodness of fit test:
    Parameter estimates for lognormal and negative binomial distributions.

Either do this as a separate script or add it into the main code.

Connolly SR, Dornelas M, Bellwood DR, Hughes TP (2009) Testing species abundance
models: A new bootstrap approach applied to Indo-Pacific coral reefs. Ecology 90(11): 3138 - 3149.

**Comment by rueuntal** [comment]
I can spend some time on this during the weekend.

**Comment by rueuntal** [comment]
It's in the new pull request. Let me know if anything looks funny.

**Comment by ethanwhite** [comment]
@embaldridge did you want to include this in the submission or leave it out for the moment?

**Comment by embaldridge** [comment]
I have no idea, as I cannot remember why I opened the issue other than presumably adding rigor?

**Comment by ethanwhite** [comment]
What it adds is a different perspective, i.e., "the data don't deviate from the Poisson-lognormal" vs. "the data fit the Poisson-lognormal better than other distributions". Based on the results in Xiao's paper I suspect, but don't know, that in most cases the data won't deviate from most of the distributions (except probably the Zipf).

So, it would be useful to add but also involve more time and energy to get implemented. I think the paper stands without it, so I think this is a judgement call on your part.

**Comment by davharris** [comment]
It wouldn't be hard to implement the tests, but I agree that the paper stands without it.

I don't really see a way that the goodness-of-fit tests could really help make the paper clearer:

* If the data does deviate substantially from all four distributions, I'm not sure what we could really say about that other than "darn. oh well." 

* If the data only deviates from some of them, we'd still be limited in what we can say because 'The Difference Between “Significant” and “Not Significant” is not
Itself Statistically Significant' [(pdf)](http://www.stat.columbia.edu/~gelman/research/published/signif4.pdf). In other words, the claim that "pln fits but zipf doesn't" wouldn't (by itself) be enough to claim that pln is better than zipf.

Neither of those really improves the paper much, in my view. The final scenario (that all the distributions fit) seems unlikely to me, given how terrible the Zipf fit is.

**Comment by davharris** [comment]
(But I'm happy to implement the tests, if the group decides it's worthwhile)

**Comment by rueuntal** [comment]
I agree with Dave.

**Comment by ethanwhite** [comment]
Sounds good to me. @embaldridge if you agree as well go ahead and close the issue.
