### ISSUE TITLE
Check if you geometric is the standard geometric

### ISSUE THREAD

**Issue by ethanwhite** [weecology/sad-comparison#176]
Some recent discussion about the geometric distribution/series raises the question of what the actual proposed version of this is for the SAD. We need to check if the geometric distribution we've been using actually matches the model in the literature.

**Comment by rueuntal** [comment]
I brought up the issue with Brian and now am pretty convinced that the geometric SAD is not the geometric distribution. Copying from Biological Diversity, page 112: 
"The first used probability distribution for SADs is the geometric, but ironically it is not actually a probability distribution but a series. The proportion of abundance in each species is a function of its rank, not a random sample from a distribution, and is different from the geometric probability distribution (May 1975). However, it is often still treated as a probability distribution. It has a single parameter, often called k or r. This represents the fraction of the remaining community captured by each successive species." 

Which probably explains why Alroy claims that an analytical solution for geometric SAD doesn't exist. It seems to me that this would belong to the same category as Alroy and Ugland et al.

**Comment by ethanwhite** [comment]
Yeah, that's my feeling as well. It's a bit disappointing to have to drop to 4 distributions, but lacking a solution for the PMF resulting from that series I think that's probably what we're left with. Thoughts @davharris?

**Comment by davharris** [comment]
Isn't the geometric distribution just a geometric series times a normalizing constant? I don't see the issue.

**Comment by rueuntal** [comment]
Dave - It is. The issue is whether the geometric series/distribution describes the SAD or the RAD, as in Alroy. My understanding at this point is that in literature the geometric has (mostly as far as I know) been applied to the RAD, ie., the most abundant species takes up x% of the total abundance, the second most abundant takes up C * x%, the third takes up C^2 * x%, and so on. But our application is on the SAD, ie. the probability of a species having abundance 1 is p, having abundance 2 is p(1-p), and so on. This doesn't translate into a geometric series of abundances for the RAD.

Does that make sense?

**Comment by davharris** [comment]
Ah, okay. Two thoughts:

1) If geometric SADs exist in the literature, then it could still make sense to include it regardless of whether the original 1975 paper actually considered it a RAD.

2) The negative binomial distribution collapses to the geometric if `n==1`. It may be possible to use this fact to make the geometric functions unnecessary.

**Comment by rueuntal** [comment]
_1) If geometric SADs exist in the literature, then it could still make sense to include it regardless of whether the original 1975 paper actually considered it a RAD._
I agree. @ethanwhite do you know of any literature that fits the geometric to the SAD?

_2) The negative binomial distribution collapses to the geometric if n==1. It may be possible to use this fact to make the geometric functions unnecessary._
I may be missing your point - are you saying that since geometric is a special case of negative binomial, it will pop out automatically from optimization if it has a good fit?

**Comment by davharris** [comment]
>are you saying that since geometric is a special case of negative binomial, it will pop out automatically from optimization if it has a good fit?

Partly. Also, we could always constrain `n` and use the negative binomial code to fit the geometric, even if we deleted the geometric code.

**Comment by rueuntal** [comment]
Sorry I'm a bit confused. Do you mean deleting the geometric from this project, or deleting the grometric functions from macroecotools (and merge them with negative binomial)?

**Comment by ethanwhite** [comment]
On 02/18/2016 10:27 PM, Xiao Xiao wrote:
> @ethanwhite <https://github.com/ethanwhite> do you know of any 
> literature that fits the geometric to the SAD?
Not off the top of my head, but I'm definitely not an expert on the use 
of geometric fits related to SADs. By the time I came along the 
geometric was largely thought of as not providing particular good fits 
so folks didn't do much with it. Of course looking back now I wonder how 
strong the analysis backing the perspective actually was.

**Comment by davharris** [comment]
I just meant that we *could* do that, if we wanted to.

**Comment by rueuntal** [comment]
Oh, sorry. Yes, totally.

**Comment by ethanwhite** [comment]
I did a looked around a little (but not a lot) and didn't find any obvious references to using the geometric distribution directly on the SAD. I guess my inclination at this point is just to pull it from the analyses.

**Comment by rueuntal** [comment]
I just did the same thing - flipped through papers on the first five pages
on Google Scholar with "species abundance distribution" and "geometric",
but they all applied geometric to the RAD. Hope we had coordinated! :p

My inclination is the same as Ethan's. In addition to not having previous
literature to back it up, using geometric in a different way may also cause
confusion to the readers.

**Comment by davharris** [comment]
Makes sense. 

Dave

**Comment by ethanwhite** [comment]
OK, thanks everyone. Closing this since it's decided.
